name: push

on:
  push:
    branches:
      - ci-llm-workflow

env:
  IMAGE_NAME_FULL: ghcr.io/nvidia/fuser:ci-llm-workflow

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: authenticate
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: build
        run: docker buildx build -f dockerfile -t ${{ env.IMAGE_NAME_FULL }} . 
      - name: push
        run: docker push ${{ env.IMAGE_NAME_FULL }}
